title: Space talk
hero_image: images/banner.png
description: Use Scratch to make sprites communicate when clicked.
version: 4
listed: false
copyedit: false
last_tested: "2021-02-09"
steps:
  - title: Introduction
  - title: Space scene
  - title: Pico plays a sound
  - title: Nano switches costume
  - title: Giga changes colour
  - title: Reflection
  - title: Tera remix
  - title: What next?
