title: Space talk
hero_image: images/banner.png
description: Use Scratch to make sprites communicate when clicked.
version: 4
listed: false
copyedit: false
last_tested: "2021-02-09"
steps:
  - title: Introduction
  - title: Create your scene
  - title: Pico plays a sound
  - title: Nano switches costumes
  - title: Giga changes colour
  - title: Reflection
  - title: Upgrade your project
  - title: What next?
