---
title: Isibhakabhaka esikhulumayo
hero_image: images/banner.png
description: Sebenzisa i-Scratch ukunikeza ama-sprites 'i-emote(ukunyakaza)' ukuze axhumane lapho achofozwa
meta_title: Amaphrojekthi okubhala ikhodi ezingane nentsha | Isingeniso ku-Scratch
meta_description: Funda ukubhala ikhodi ku-Scratch ngamaphrojekthi okubhala ikhodi nge-Raspberry Pi Foundation yezingane nentsha. Yenza opopayi be-Scratch, imidlalo, izinhlelo zokusebenza, nokuningi.
pdf: resources/space-talk.pdf
listed: true
copyedit: false
last_tested: "2021-02-09"
steps:
  - 
    title: What you will make
  - 
    title: Qala isigcawu sakho
  - 
    title: U-Pico uthi sawubona
    completion:
      - engaged
  - 
    title: U-Pico udlala umsindo
  - 
    title: U-Nano ushintsha izingubo
  - 
    title: Nano signs "Thanks!"
  - 
    title: Giga changes colour
    completion:
      - internal
  - 
    title: Quick quiz
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - 
    title: Upgrade your project
