---
title: Svemirski razgovor
hero_image: images/banner.png
description: Upotrijebite Scratch kako bi ste dali likovima "emociju" da komuniciraju kada se kliknu
meta_title: Projekti scratch programiranja za djecu i tinejdžere | Uvod u Scratch
meta_description: Naučite programirati u Scratchu uz projekte programiranja Zaklade Raspberry Pi za djecu i tinejdžere. Napravite Scratch animacije, igre, aplikacije i još puno toga.
pdf: resources/space-talk.pdf
listed: true
copyedit: false
last_tested: "2021-02-09"
steps:
  - 
    title: Vi ćete napraviti
  - 
    title: Kreirajte svoju scenu
  - 
    title: Pico kaže bok
    completion:
      - engaged
  - 
    title: Pico pušta zvuk
  - 
    title: Nano mijenja kostime
  - 
    title: Nano signs "Thanks!"
  - 
    title: Giga changes colour
    completion:
      - internal
  - 
    title: Quick quiz
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - 
    title: Upgrade your project
