---
title: Sgwrs yn y Sêr
hero_image: images/banner.png
description: Defnyddio Scratch i roi 'emoshlun' i gymeriadau corlun fel eu bod yn cyfathrebu ar ôl eu clicio
meta_title: Scratch coding projects for kids and teens | Intro to Scratch
meta_description: Learn to code in Scratch with the Raspberry Pi Foundation's coding projects for kids and teens. Make Scratch animations, games, apps, and more.
pdf: resources/space-talk.pdf
listed: true
copyedit: false
last_tested: "2021-02-09"
steps:
  - 
    title: What you will make
  - 
    title: Creu eich golygfa
  - 
    title: Pico yn dweud helo
    completion:
      - engaged
  - 
    title: Pico yn chwarae sain
  - 
    title: Nano yn newid gwisgoedd
  - 
    title: Giga yn newid lliw
  - 
    title: Myfyrio
    completion:
      - internal
  - 
    title: Uwchraddio dy brosiect
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - 
    title: Upgrade your project
