---
title: Weltraumgespräch
hero_image: images/banner.png
description: Verwende Scratch, um Figuren ein „Emote“ zu geben, damit sie kommunizieren, wenn sie angeklickt werden
meta_title: Scratch Coding Projekte für Kinder und Jugendliche | Einführung in Scratch
meta_description: Lerne programmieren (coden) in Scratch mit den Coding Projekten der Raspberry Pi Foundation für Kinder und Jugendliche. Erstelle Scratch-Animationen, Spiele, Apps und mehr.
listed: true
copyedit: false
last_tested: "2021-02-09"
steps:
  - 
    title: Was du machen wirst
  - 
    title: Erstelle deine Szene
  - 
    title: Pico sagt "Hallo"
    completion:
      - engaged
  - 
    title: Pico spielt einen Ton ab
  - 
    title: Nano wechselt Kostüme
  - 
    title: Giga ändert die Farbe
    completion:
      - internal
  - 
    title: Kurzes Quiz
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - 
    title: Mach dein Projekt noch cooler
  - 
    title: Wie geht es weiter?
