---
title: ಬಾಹ್ಯಾಕಾಶ ಮಾತುಕತೆ
hero_image: images/banner.png
description: ಸ್ಪ್ರೈಟ್‌ಗೆ ʼಅಭಿನಯʼ ಕೊಡಲು Scratch ಉಪಯೋಗಿಸಿ, ಅದರಿಂದ ಕ್ಲಿಕ್‌ ಮಾಡಿದಾಗ ಅವು ತಿಳಿಸುತ್ತವೆ
meta_title: Scratch coding projects for kids and teens | Intro to Scratch
meta_description: Learn to code in Scratch with the Raspberry Pi Foundation's coding projects for kids and teens. Make Scratch animations, games, apps, and more.
pdf: resources/space-talk.pdf
listed: true
copyedit: false
last_tested: "2021-02-09"
steps:
  - 
    title: What you will make
  - 
    title: ನಿಮ್ಮ ದೃಶ್ಯವನ್ನು ಇಲ್ಲಿ ರಚಿಸಿ
  - 
    title: Pico ಹಲೋ ಹೇಳುತ್ತಾನೆ
    completion:
      - engaged
  - 
    title: Pico ಧ್ವನಿಯನ್ನು ನುಡಿಸುತ್ತಾನೆ
  - 
    title: Nano ಉಡುಪುಗಳನ್ನು ಬದಲಾಯಿಸುತ್ತದೆ
  - 
    title: Giga ಬಣ್ಣವನ್ನು ಬದಲಾಯಿಸುತ್ತದೆ
  - 
    title: ಪುನರ್ಮನನ
    completion:
      - internal
  - 
    title: ನಿಮ್ಮ ಪ್ರಾಜೆಕ್ಟ್‌ ಅಪ್‌ಗ್ರೇಡ್‌ ಮಾಡಿ
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - 
    title: Upgrade your project
