---
title: Conversación espacial
hero_image: images/banner.png
description: Usa Scratch para darle una 'emoción' a los objetos para que se comuniquen cuando se hace clic en ellos
meta_title: Scratch coding projects for kids and teens | Intro to Scratch
meta_description: Learn to code in Scratch with the Raspberry Pi Foundation's coding projects for kids and teens. Make Scratch animations, games, apps, and more.
listed: true
copyedit: false
last_tested: "2021-02-09"
steps:
  - 
    title: Lo que harás
  - 
    title: Crea tu escena
  - 
    title: Pico dice hola
    completion:
      - engaged
  - 
    title: Pico reproduce un sonido
  - 
    title: Nano cambia de disfraz
  - 
    title: Giga cambia de color
    completion:
      - internal
  - 
    title: Examen rápido
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - 
    title: Mejora tu proyecto
  - 
    title: '¿Qué sigue?'
