---
title: Conversación espacial
hero_image: images/banner.png
description: Usa Scratch para darle un 'emote' a los objetos para que se comuniquen cuando se hace clic en ellos
version: 4
listed: true
copyedit: false
last_tested: "2021-02-09"
steps:
  - 
    title: Introducción
  - 
    title: Crea tu escena
  - 
    title: Pico dice hola
    completion: engaged
  - 
    title: Pico reproduce un sonido
  - 
    title: Nano cambia de disfraz
  - 
    title: Giga cambia de color
    completion: internal
  - 
    title: Reflexión
    completion: external
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
  - 
    title: Mejora tu proyecto
  - 
    title: '¿Qué sigue?'
