---
title: Kosmiczna rozmowa
hero_image: images/banner.png
description: Użyj Scratcha, aby dać duszkom „emotkę”, tak by komunikowały się po kliknięciu
meta_title: Scratch coding projects for kids and teens | Intro to Scratch
meta_description: Learn to code in Scratch with the Raspberry Pi Foundation's coding projects for kids and teens. Make Scratch animations, games, apps, and more.
listed: true
copyedit: false
last_tested: "2021-02-09"
steps:
  - 
    title: You will make
  - 
    title: Stwórz swoją scenę
  - 
    title: 'Pico mówi: "cześć"'
    completion:
      - engaged
  - 
    title: Pico odtwarza dźwięk
  - 
    title: Nano zmienia kostiumy
  - 
    title: Giga zmienia kolor
    completion:
      - internal
  - 
    title: Quick quiz
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - 
    title: Ulepsz swój projekt
  - 
    title: Co dalej?
