---
title: Kosmiczna rozmowa
hero_image: images/banner.png
description: Użyj Scratcha, aby dać duszkom „emotkę”, tak by komunikowały się po kliknięciu
meta_title: Projekty programistyczne Scratch dla dzieci i młodzieży | Wprowadzenie do Scratcha
meta_description: Naucz się programować w języku Scratch dzięki projektom programistycznym Fundacji Raspberry Pi dla dzieci i nastolatków. Twórz animacje Scratch, gry, aplikacje i nie tylko.
listed: true
copyedit: false
last_tested: "2021-02-09"
steps:
  - title: Co będziesz robić
  - title: Stwórz swoją scenę
  - title: 'Pico mówi: "cześć"'
    completion:
      - engaged
  - title: Pico odtwarza dźwięk
  - title: Nano zmienia kostiumy
  - title: Giga zmienia kolor
    completion:
      - internal
  - title: Szybki quiz
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - title: Ulepsz swój projekt
  - title: Co dalej?
