---
title: Rymdsamtal
hero_image: images/banner.png
description: Använd Scratch för att ge sprajts gester som de kan kommunicera med när de blir klickade
version: 4
listed: true
copyedit: false
last_tested: "2021-02-09"
steps:
  - title: Du kommer att skapa
  - title: Skapa din scen
  - title: Pico säger hej
    completion:
      - engaged
  - title: Pico spelar ett ljud
  - title: Nano byter klädsel
  - title: Giga byter färg
    completion:
      - internal
  - title: Snabbt quiz
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - title: Uppgradera ditt projekt
  - title: Vad händer nu?
