---
title: Ομιλία στο διάστημα
hero_image: images/banner.png
description: Χρησιμοποίησε το Scratch για να δώσεις στα αντικείμενα μια 'έκφραση' ώστε να επικοινωνούν όταν γίνεται κλικ πάνω τους
meta_title: Έργα κώδικα σε Scratch για παιδιά και εφήβους | Εισαγωγή στη Scratch
meta_description: Μάθε να προγραμματίζεις στη Scratch με τα έργα κώδικα του Ιδρύματος Raspberry Pi για παιδιά και εφήβους. Δημιούργησε κινούμενα σχέδια, παιχνίδια, εφαρμογές και άλλα.
pdf: resources/space-talk.pdf
listed: true
copyedit: false
last_tested: "2021-02-09"
steps:
  - 
    title: What you will make
  - 
    title: Δημιούργησε την σκηνή σου
  - 
    title: Ο Pico λέει γεια
    completion:
      - engaged
  - 
    title: Ο Pico παίζει έναν ήχο
  - 
    title: Ο Nano αλλάζει ενδυμασίες
  - 
    title: Ο Giga αλλάζει χρώμα
  - 
    title: Γρήγορο κουίζ
    completion:
      - external
  - 
    title: Αναβάθμισε το έργο σου
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - 
    title: Upgrade your project
