---
title: Parler de l'espace
hero_image: images/banner.png
description: Utiliser Scratch pour donner aux sprites une « émotion » afin qu'ils communiquent lorsqu'ils sont cliques
meta_title: Projets de codage scratch pour enfants et adolescents | Intro à Scratch
meta_description: Apprends à coder avec Scratch avec les projets de codage de la Raspberry Pi Foundation pour les enfants et les adolescent·e·s. Réalise des animations Scratch, des jeux, des applications, et bien plus encore.
pdf: resources/space-talk.pdf
listed: true
copyedit: false
last_tested: "2021-02-09"
steps:
  - 
    title: Ce que tu vas faire
  - 
    title: Créer ta scène
  - 
    title: Pico dit bonjour
    completion:
      - engaged
  - 
    title: Pico joue un son
  - 
    title: Nano change de costume
  - 
    title: Nano fait signe « Merci ! »
  - 
    title: Giga change de couleur
    completion:
      - internal
  - 
    title: Questionnaire rapide
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - 
    title: Améliorer ton projet
