---
title: Conversazione spaziale
hero_image: images/banner.png
description: Utilizza Scratch per dare un'espressione (emote) agli sprite per farli parlare quando vengono cliccati
meta_title: Progetti di programmazione con Scratch per bambini e ragazzi | Introduzione a Scratch
meta_description: Impara a programmare usando Scratch con i progetti di programmazione per bambini e ragazzi offerti dalla Raspberry Pi Foundation. Fai animazioni con Scratch, giochi, app e altro ancora.
pdf: resources/space-talk.pdf
listed: true
copyedit: false
last_tested: "2021-02-09"
steps:
  - 
    title: Quello che farai
  - 
    title: Crea la tua scena
  - 
    title: Pico dice Ciao
    completion:
      - engaged
  - 
    title: Pico riproduce un suono
  - 
    title: Nano cambia il costume
  - 
    title: Giga cambia il colore
  - 
    title: Quiz veloce
    completion:
      - external
  - 
    title: Migliora il tuo progetto
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - 
    title: Upgrade your project
